learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r"", include("learning_logs.urls")),   # 主页，管理员功能
    path(r"users/", include("users.urls")),      # 用户

]

learning_logs/urls.py
"""定义learning_logs中的URL模式"""

from django.urls import path
from . import views

app_name = "learning_logs"

urlpatterns = [
    path(r"", views.index, name="index"),                                           # 主页
    path(r"topics/", views.topics, name="topics"),                                  # 主题
    path(r"topics/<int:topic_id>/", views.topic, name="topic"),                     # 特定主题的详细页
    path(r"new_topic/", views.new_topic, name="new_topic"),                         # 添加新主题
    path(r"new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),          # 添加新条目
    path(r"edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),       # 编辑条目

]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "users"

urlpatterns = [
    path(r"login/", LoginView.as_view(template_name="users/login.html"), name="login"),     # 登录
    path(r"logout/", views.logout_view, name="logout"),                                       # 登出
    path(r"register/", views.register, name="register"),                                      # 注册

]


learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_logs/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """学习笔记的主页"""
    return render(request, "learning_logs/index.html")

@login_required
def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != "POST":
        # 未提交数据，创建一个新表单
        form = TopicForm()
    else:
        # POST提交数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse("learning_logs:topics"))

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)

@login_required
def new_entry(request, topic_id):
    """添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        print(form)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse("learning_logs:topic", args=[topic_id]))
    context = {"form": form, "topic": topic}
    return render(request, "learning_logs/new_entry.html", context)

@login_required
def edit_entry(request, entry_id):
    # 编辑既有条目
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != "POST":
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("learning_logs:topic", args=[topic.id]))

    context = {"topic": topic, "entry": entry, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect


# Create your views here.


def logout_view(request):
    """用户登出"""
    logout(request)
    return HttpResponseRedirect(reverse("learning_logs:index"))

def register(request):
    """用户注册"""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到首页
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST["password1"])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse("learning_logs:index"))
    context = {"form": form}
    return render(request, "users/register.html", context)

learning_logs/templates/learning_logs/base.html
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
{% load bootstrap3 %}

<! DOCTYPE html>
<html lang="zh">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatiblr" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=-">

        <title>Learning Log</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-expanded="false"
                aria-controls="navbar" data-target="#navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello,{{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                    <li><a href="{% url 'users:login' %}">Log in</a></li>
                    {% endif%}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %} {% endblock header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>
    </div>


    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html "%}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit Entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token%}
        {{ form.as_p}}
        <button name="submit">save changes</button>
    </form>

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block header %}
    <div class="jumbotron">
        <h1>Track your learning .</h1>
    </div>
    {% endblock header %}

    {% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a>to make
        your own Learning Log,and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic,make a entry
        summarizing what you've learned.
    </h2>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
</form>

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% block buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
        {% endblock buttons %}
    </form>
{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p><a href="{% url 'learning_logs:new_entry' topic.id%}">add new entry</a></p>

    {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:"M d, Y H:i"}}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry</a>
                </small>
            </h3>
        </div>
        <div class="panel-boby">
            {{ entry.text|linebreaks }}
        </div>

    </div>
    {% empty%}
    <h2>There are no entries for this topic yet.</h2>
    {% endfor %}

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <ul>
        {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
        {% empty %}
        <h2>No topics have been added yet.</h2>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">add a new topic</a></h3>
{% endblock content %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token%}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}

</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="submit">register</button>
    <input name="next" type="hidden" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}
</body>
</html>